### PR TITLE
RF: migrate from using nose for testing to pytest 

### LINKED ISSUE #66: Move over to pytest from nose
discovered while looking how come tests are still passing after #63 from core was merged and apparently deprecated is still nose based.

### PR DESCRIPTION
**Pull request by yarikoptic**
- demonstrates various changes needed to migrate this one to pytest instead of nose
- already relies on semi-complete **Choice 1** of https://github.com/datalad/datalad/pull/6273 in minimal impact on extensions
- I have even attempted "what if we try to make this pytest migrated extension compatible with both old nose-based and new pytest-based datalad core" by changes in conftest.py to create the `setup_package` based on old nose based fixtures. But it is not enough due to `assert_raises` context manager has `.value` instead of `.extension` and we import some tests from datalad core.
- [x] Remove TEMP commit installing datalad from a branch and add corresponding versioned dependency to setup.cfg (well -- did not remove commit but just removed the change upon merging master and resolving conflict)
- somewhat contingent on having test markers defined "in code" or we would need to duplicate relevant ones here in tox.ini: https://github.com/datalad/datalad/issues/6654 (unfortunately no good solution was devised AFAIK)
- [x] fixed up testing on crippled filesystems -- some tests were devised before adjusted mode became the thing I guess. Some other I skipped (we do not even test them in core :-/)
  - [x] some tests were marked as `skip_if_adjusted_branch` instead of just skipping on windows
- [x] fixed up testing of recently moved metadata
- [x] fixed up bundling of data files in sdist and wheels

Closes #66

### CODE REVIEW

**Comment by yarikoptic** [comment]
<details>
<summary>fails here: 18 failed, 29 passed, 17 skipped, 89 warnings in 238.48s -- 64 total</summary> 

```shell
=========================== short test summary info ============================
FAILED ../tests/test_annotate_paths.py::test_get_modified_subpaths - Assertio...
FAILED ../tests/test_auto.py::test_proxying_open_testrepobased - Failed: DID ...
FAILED ../tests/test_auto.py::test_proxying_open_h5py - AssertionError
FAILED ../tests/test_auto.py::test_proxying_open_regular - AssertionError
FAILED ../tests/test_auto.py::test_proxying_io_open_regular - AssertionError
FAILED ../tests/test_auto.py::test_proxying_lzma_LZMAFile - _lzma.LZMAError: ...
FAILED ../tests/test_auto.py::test_proxying_open_nibabel - nibabel.filebasedi...
FAILED ../tests/test_auto.py::test_proxying_os_stat - AssertionError: assert ...
FAILED ../tests/test_create_sibling_webui.py::test_preserve_attrs - assert 12...
FAILED ../tests/test_diff.py::test_diff - AssertionError: Got 0 instead of 1 ...
FAILED ../tests/test_diff.py::test_diff_recursive - AssertionError: Got 0 ins...
FAILED ../tests/test_diff.py::test_diff_helper - AssertionError: Got 4 instea...
FAILED ../tests/test_ls_webui.py::test_ls_json - AttributeError: 'NoneType' o...
FAILED ../tests/test_publish.py::test_since_empty_and_unsupported - datalad.s...
FAILED ../tests/test_publish.py::test_publish_simple - AssertionError: Got 0 ...
FAILED ../tests/test_publish.py::test_publish_recursive - datalad.support.exc...
FAILED ../tests/test_publish.py::test_publish_with_data - datalad.support.exc...
FAILED ../tests/test_publish.py::test_gh1426 - datalad.support.exceptions.Inc...
====== 18 failed, 29 passed, 17 skipped, 89 warnings in 238.48s (0:03:58) ======
```
</details>

and in a fresh PR #52 to see how master is doing with nose:

<details>
<summary> Ran 71 tests in 263.468s   FAILED (SKIP=17, errors=12, failures=12) -- 30 pass if algebra is right</summary> 

```shell
datalad@smaug:/mnt/datasets/datalad/ci/datalad-deprecated/2022/04/28/pr/52/30e7257/github-crippled-filesystems-51-failed$ grep -e '\(ERROR\|FAIL\):' test/8_Run\ tests.txt  | nl
     1  2022-04-28T15:49:43.5995618Z ERROR: datalad_deprecated.tests.test_auto.test_proxying_lzma_LZMAFile(<function test_proxying_lzma_LZMAFile.<locals>.generate_dat at 0x7fbebc05add0>, <function test_proxying_lzma_LZMAFile.<locals>.verify_dat at 0x7fbebc030440>)
     2  2022-04-28T15:49:43.6124495Z ERROR: datalad_deprecated.tests.test_auto.test_proxying_open_nibabel(<function test_proxying_open_nibabel.<locals>.generate_nii at 0x7fbea2d2dd40>, <function test_proxying_open_nibabel.<locals>.verify_nii at 0x7fbebc04d680>)   
     3  2022-04-28T15:49:43.6133455Z ERROR: datalad_deprecated.tests.test_create_sibling_webui.test_target_ssh_recursive(False,)
     4  2022-04-28T15:49:43.6148023Z ERROR: datalad_deprecated.tests.test_create_sibling_webui.test_target_ssh_since(False,)
     5  2022-04-28T15:49:43.6154795Z ERROR: datalad_deprecated.tests.test_create_sibling_webui.test_replace_and_relative_sshpath(False,)
     6  2022-04-28T15:49:43.6199232Z ERROR: datalad_deprecated.tests.test_create_sibling_webui.test_target_ssh_inherit('backup', False, False)
     7  2022-04-28T15:49:43.6213651Z ERROR: datalad_deprecated.tests.test_ls_webui.test_ls_json
     8  2022-04-28T15:49:43.6220148Z ERROR: datalad_deprecated.tests.test_publish.test_target_ssh_inherit('backup', False, False)
     9  2022-04-28T15:49:43.6239371Z ERROR: datalad_deprecated.tests.test_publish.test_gh1426
    10  2022-04-28T15:49:43.6251938Z ERROR: datalad_deprecated.tests.test_publish.test_since_empty_and_unsupported
    11  2022-04-28T15:49:43.6264670Z ERROR: datalad_deprecated.tests.test_publish.test_publish_recursive
    12  2022-04-28T15:49:43.6347100Z ERROR: datalad_deprecated.tests.test_publish.test_publish_with_data
    13  2022-04-28T15:49:43.6361088Z FAIL: datalad_deprecated.tests.test_annotate_paths.test_get_modified_subpaths
    14  2022-04-28T15:49:43.6368538Z FAIL: datalad_deprecated.tests.test_auto.test_proxying_open_h5py(<function test_proxying_open_h5py.<locals>.generate_hdf5 at 0x7fbebbe10b00>, <function test_proxying_open_h5py.<locals>.verify_hdf5 at 0x7fbebbe104d0>)
    15  2022-04-28T15:49:43.6373209Z FAIL: datalad_deprecated.tests.test_auto.test_proxying_open_regular(<function test_proxying_open_regular.<locals>.generate_dat at 0x7fbebc073cb0>, <function test_proxying_open_regular.<locals>.verify_dat at 0x7fbebc0738c0>)   
    16  2022-04-28T15:49:43.6378341Z FAIL: datalad_deprecated.tests.test_auto.test_proxying_io_open_regular(<function test_proxying_io_open_regular.<locals>.generate_dat at 0x7fbebc016680>, <function test_proxying_io_open_regular.<locals>.verify_dat at 0x7fbebbe10320>)
    17  2022-04-28T15:49:43.6383583Z FAIL: datalad_deprecated.tests.test_auto.test_proxying_os_stat(<function test_proxying_os_stat.<locals>.generate_dat at 0x7fbebbc727a0>, <function test_proxying_os_stat.<locals>.verify_dat at 0x7fbebbc72ef0>)
    18  2022-04-28T15:49:43.6388056Z FAIL: datalad_deprecated.tests.test_auto.test_proxying_open_testrepobased
    19  2022-04-28T15:49:43.6392518Z FAIL: datalad_deprecated.tests.test_create_sibling_webui.test_failon_no_permissions(False,)
    20  2022-04-28T15:49:43.6399817Z FAIL: datalad_deprecated.tests.test_create_sibling_webui.test_preserve_attrs
    21  2022-04-28T15:49:43.6405885Z FAIL: datalad_deprecated.tests.test_diff.test_diff_helper
    22  2022-04-28T15:49:43.6422432Z FAIL: datalad_deprecated.tests.test_diff.test_diff
    23  2022-04-28T15:49:43.6429193Z FAIL: datalad_deprecated.tests.test_diff.test_diff_recursive
    24  2022-04-28T15:49:43.6436482Z FAIL: datalad_deprecated.tests.test_publish.test_publish_simple
```
</details>

**Comment by yarikoptic** [comment]
windows and crippled and even ubuntu seems to error out with

```
collected 98 items / 1 error / 4 skipped                                                                                                                                                                                                       
==================================================================================================================== ERRORS ====================================================================================================================
_________________________________________________________________________________________________ ERROR collecting metadata/extractors/xmp.py __________________________________________________________________________________________________
../../../dlvenv/lib/python3.8/site-packages/datalad_deprecated/metadata/extractors/xmp.py:20: in <module>
    from libxmp.utils import file_to_dict
../../../dlvenv/lib/python3.8/site-packages/libxmp/__init__.py:50: in <module>
    from .core import XMPMeta, XMPIterator
../../../dlvenv/lib/python3.8/site-packages/libxmp/core.py:50: in <module>
    from . import exempi as _cexempi
../../../dlvenv/lib/python3.8/site-packages/libxmp/exempi.py:69: in <module>
    EXEMPI = _load_exempi()
../../../dlvenv/lib/python3.8/site-packages/libxmp/exempi.py:60: in _load_exempi
    raise ExempiLoadError('Exempi library not found.')
E   libxmp.ExempiLoadError: Exempi library not found.
```
looking into it

**Comment by yarikoptic** [comment]
many of "crippled" tests fail due to what looks like broken packaging of the datalad-deprecated as not shipping the test data
```
2022-09-29T14:26:19.5528040Z         if not follow_symlinks and os.path.islink(src):
2022-09-29T14:26:19.5528328Z             os.symlink(os.readlink(src), dst)
2022-09-29T14:26:19.5528555Z         else:
2022-09-29T14:26:19.5528825Z >           with open(src, 'rb') as fsrc:
2022-09-29T14:26:19.5529453Z E           FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/datalad_deprecated/metadata/tests/data/exif.jpg'
2022-09-29T14:26:19.5529771Z 
2022-09-29T14:26:19.5529960Z /opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/shutil.py:120: FileNotFoundError
2022-09-29T14:26:19.5530575Z ------------------------------ Captured log call -------------------------------
```
and in crippled we install via `python -m pip install .` so non-devel mode while in appveyor we do both
```
  - python -m pip install -r requirements-devel.txt
  - python -m pip install .
```
and we have 

```
$> head requirements-devel.txt 
# requirements for a development environment
-e .[devel]
```

so I guess we do test "in place" installation and thus finding the data files...

**Comment by yarikoptic** [comment]
woohoo -- appveyor is green . 

<details>
<summary>crippled still has 16 failing I will look into later/separately ... forgot to push some fixes -- will push soon</summary> 

```shell
FAILED ../tests/test_auto.py::test_proxying_open_testrepobased - Failed: DID ...
FAILED ../tests/test_auto.py::test_proxying_open_h5py - AssertionError
FAILED ../tests/test_auto.py::test_proxying_open_regular - AssertionError
FAILED ../tests/test_auto.py::test_proxying_io_open_regular - AssertionError
FAILED ../tests/test_auto.py::test_proxying_lzma_LZMAFile - _lzma.LZMAError: ...
FAILED ../tests/test_auto.py::test_proxying_open_nibabel - nibabel.filebasedi...
FAILED ../tests/test_auto.py::test_proxying_os_stat - AssertionError: assert ...
FAILED ../tests/test_create_sibling_webui.py::test_target_ssh_recursive - dat...
FAILED ../tests/test_create_sibling_webui.py::test_preserve_attrs - assert 12...
FAILED ../tests/test_diff.py::test_diff_helper - AssertionError: Got 4 instea...
FAILED ../tests/test_ls_webui.py::test_ls_json - AttributeError: 'NoneType' o...
FAILED ../tests/test_publish.py::test_since_empty_and_unsupported - datalad.s...
FAILED ../tests/test_publish.py::test_publish_simple - AssertionError: Got 0 ...
FAILED ../tests/test_publish.py::test_publish_recursive - datalad.support.exc...
FAILED ../tests/test_publish.py::test_publish_with_data - datalad.support.exc...
FAILED ../tests/test_publish.py::test_gh1426 - datalad.support.exceptions.Inc...
```
</details>

also need to figure out why codecov is not reporting back, into statuses but it is [known](https://app.codecov.io/gh/datalad/datalad-deprecated/pull/51) and shows above that we improve by 23% ;)

**Comment by yarikoptic** [comment]
ok -- it is very green. I will merge and release tomorrow unless any "stop" is voiced or feedback requiring changes is provided.

**Review by christian-monch — APPROVED** [review]
LGTM, Thx a lot @yarikoptic

**Pull request merged**
